### ISSUE TITLE
ExampleResources/playerblips: Blips appear midmap when players are out of stream range

### ISSUE THREAD

**Issue by dennorske** [GTANetworkDev/ExampleResources#2]
Hello! 

Don't have time to provide a fix myself, and quite unfamiliar with the JS still. However the default code makes the blips appear mid-town (around Vinewood hills) when a player is too far away from other player(s). This causes the blip to appear somewhere invalid. (0.0,0.0,0.0?)

Can this be made server-based so server shares the position, rather than the client fetching position from streamed-in players ?

**Comment by MissyMelissa** [comment]
Yes, there's [this bugreport](https://bt.gtanet.work/view.php?id=10) which is causing this issue. Once that is fixed, the playerblips resource itself will be fixed as well.

I use a workaround for this in [my playerblips resource](https://github.com/MissyMelissa/playerblips-pro). I'm considering doing a pull request to replace the existing playerblips resource with this one, if people are interested?

**Comment by dennorske** [comment]
That looks freaking awesome, would be a very nice addition for the Default resource set. 
Thanks for the reply, wasn't quite aware of the bug 😄
